name: Build and Release on Playstore

on:
  push:
    branches:
      - master
  workflow_dispatch: { }

permissions:
  contents: write
  id-token: write

jobs:
  build:
    if:  github.event_name == 'workflow_dispatch' || startsWith(github.event.head_commit.message, '[release]')
    runs-on: ubuntu-latest
    env:
      VERSION: $( echo ${{ github.event.head_commit.id }} | cut -c1-7 )
      COMMIT: $( sed -E "s/(.*) <.*@.*>/\\1/g;t" <<< "${{ github.event.head_commit.message }}" | jq -Rsa . | tail -c +2 | head -c -2 )
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: 'gradle'

      - name: Extract Version Name from Gradle
        run: |
          GRADLE_FILE="app/build.gradle.kts" 
          VERSION_NAME=$(grep -E 'val appVersionName' $GRADLE_FILE | head -n 1 | awk -F'"' '{print $2}')

          if [ -z "$VERSION_NAME" ]; then
            echo "::error::Could not extract version name from $GRADLE_FILE."
            exit 1
          fi

          echo "Extracted Version: $VERSION_NAME"
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV

      - name: Extract Changelog Notes
        run: |
          VERSION="${{ env.VERSION_NAME }}"
          CHANGELOG_FILE="CHANGELOG.md"
          # Create a directory for the upload action to find
          mkdir -p distribution/whatsnew
          
          sed -n "/## ${VERSION}/, /## [0-9]/p" ${CHANGELOG_FILE} | \
          sed '1d;$d' | grep -v '^# Changelog' > distribution/whatsnew/whatsnew-en-US
          
          if [ ! -s "distribution/whatsnew/whatsnew-en-US" ]; then
             echo "Default changelog for ${{ env.VERSION_NAME }}" > distribution/whatsnew/whatsnew-en-US
          fi

      - name: Cook KeyStore
        run: echo "${{ secrets.KEYSTORE_FILE }}" | base64 -d > $GITHUB_WORKSPACE/signing-key.jks

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Inject Genius API Key
        run: echo "GENIUS_API_PRIVATE=${{ secrets.GENIUS_API_PRIVATE }}" >> local.properties

      - name: Build with Gradle
        run: |
          ./gradlew bundlePlayRelease \
          -Pandroid.injected.signing.store.file=$GITHUB_WORKSPACE/signing-key.jks \
          -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASSWORD }} \
          -Pandroid.injected.signing.key.alias=key0 \
          -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }}
          
          AAB_PATH=$(find app/build/outputs/ -name "*.aab" -print -quit)
          
          if [ -z "$AAB_PATH" ]; then
            echo "::error::Could not find AAB file."
            exit 1
          fi
          
          echo "AAB_PATH=$AAB_PATH" >> $GITHUB_ENV

      - name: Setup Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ secrets.WORKLOAD_IDENTITY_POOL }}/providers/${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ secrets.WORKLOAD_IDENTITY_SERVICE_ACCOUNT }}'

      - name: Publish Release
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: ${{ steps.auth.outputs.credentials_file_path }}
          releaseFiles: ${{ env.AAB_PATH }}
          packageName: com.shub39.rush.play
          tracks: production
          whatsNewDirectory: distribution/whatsnew
